apiVersion : apps/v1
kind: Deployment
metadata:
  name: ksapplication
  namespace: myakscluster-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksapplication
  template:
    metadata:
      labels:
        app: ksapplication 
    spec:
      containers:
        - name: ksapplication 
          image: myaksclusteracr720.azurecr.io/ksapplication:$(Build.BuildId)
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: ghostauacr8f8b-auth



